### ISSUE TITLE
The pin for cryptobullionpools gets autogenerated 

### ISSUE THREAD

**Issue by fintrader** [Hou5e/FoldingBrowser#1]
How do we know what the pin is when trying to login? The captcha is there but not the pin

**Comment by Hou5e** [comment]
The CureCoin pool pin info can be found in the 'Saved Data', when you click the 'Tools' checkbox in the FoldingBrowser:

![curecoinpoolpininfo](https://cloud.githubusercontent.com/assets/20870053/22700863/d4e2fa58-ed10-11e6-8bb1-605b26c11e10.jpg)
