### ISSUE TITLE
FoldingBrowser v8 temporary UI freezes => fixed in FoldingBrowser v9

### ISSUE THREAD

**Issue by informatorius** [Hou5e/FoldingBrowser#2]
I tried FoldingBrowser v8 and got often temporary UI freezes where browser is all grey when browser was minimized and then maximized again. It took a minute until browser content was rendered again.

I then tried FoldingBrowser v9 from source and it is fixed. 
(Only about 1 sec the UI is freezed in grey when minimize and then maximize.)

**Comment by Hou5e** [comment]
Thanks for reporting this issue and testing out the new version. It appears to be an issue in CefSharp v53.0.1 (used in FoldingBrowser v7 and v8).

I only saw this happen in the past when I was doing CPU & GPU folding and running the FoldingBrowser with CefSharp v53.0.1. GPU-only folding and running the FoldingBrowser seemed to be OK for me (v55 or v53.0.1 versions).

There is a related issue where CefSharp v53.0.1 hangs on exiting sometimes. This seems to happen only when there are Java events running while closing the browser. I tried to minimize this issue by displaying a blank page before shutting down CefSharp v53.0.1. Using the newer CefSharp v55 seems to have fixed that issue.

Also, if you go to: nomachine.com  [The NoMachine web page doesn't load with v53.0.1, but does load in v55]
