### ISSUE TITLE
Does not open windows 7

### ISSUE THREAD

**Issue by ghost** [Hou5e/FoldingBrowser#3]
Foldingcoin browser is breaking for me on windows 7.

I tried both v12 and v11. I have installed https://support.microsoft.com/en-us/help/3179560/update-for-visual-c-2013-and-visual-c-redistributable-package

**Comment by JeffMore1and** [comment]
Please verify that you've installed the x86 version from about halfway down on the webpage link that you posted. The x64 and x86versions can both be installed without causing any conflicts.

Also, please verify that you've installed .NET Framework v4.5.2 or higher.

(I'll be on vacation for about another week, and won't have access to help until I'm back.)

**Comment by Hou5e** [comment]
Typically, just installing the VC++ 2013 ***x86*** Redist package fixes this issue. Please feel free to reopen this issue if it doesn't. Thanks!
