### ISSUE TITLE
Web control keeps reloading

### ISSUE THREAD

**Issue by lamert** [Hou5e/FoldingBrowser#4]
Hi guys,

I have an issue with the web control while mining. When I open web control, the browser keeps refreshing.
The client keeps mining. Already tried a reboot and yesterday everything was working fine.

Anybody got any ideas on what to doe?

**Comment by Hou5e** [comment]
Thanks for the bug report. Can you send some more details though:
1. Which web browser is having the refreshing problem (and which version)?
2. Which version of Windows are you running?
3. Did you use the FoldingBrowser to setup Folding@Home, or are you running a beta version of Folding@Home?
4. Is the Folding@Home software running in the system tray when you are viewing the web page? (It needs to be)

Things you can try:
 -Hit F5, or Ctrl+F5 to manually refresh the web page in the FoldingBrowser.
 -You can close the FoldingBrowser, and manually delete the stored files on your PC by
   deleting files in this folder:  C:\Users\\{Username}\AppData\Roaming\FoldingBrowser\Cache
   Then try opening the web control page in the FoldingBrowser again.
 -You can click the 'Tools' button in the FoldingBrowser and there is a text-based log file of events that might be useful.

Any updates would be appreciated. Thanks!

**Comment by lamert** [comment]
I found out that it happends on Chrome (Versie 59.0.3071.115 (Official build) (64-bits) )when opening web control.
When using Foldingbrowser, everything works fine.

I'm running Windows 10 and I'm not running the beta version.
The Folding@home software is on.

Thanks for all the answers. I'm gonna go on using the folding browser. It works for me, thanks.
