### ISSUE TITLE
password and pin

### ISSUE THREAD

**Issue by rickrs** [Hou5e/FoldingBrowser#5]
how i get them? its automatic, i really want change to my own passwords. i dont have the pin. cause foldingbrowser generate a new one, and not informed me.

**Comment by Hou5e** [comment]
Please see the image below:
![image](https://user-images.githubusercontent.com/20870053/29503417-67190c7c-85ec-11e7-83ef-ca574dc41d43.png)

All the saved settings are in the Tools check box, Saved Data button, then check the Show Passwords checkbox.

If you change your passwords, you can update the FoldingBrowser with the new passwords and press the Save Changes button to save the changes to the encrypted settings file. NOTE: Some of the passwords can't be changed once they have been chosen by the FoldingBrowser.

Please let me know if you still need help.

**Comment by rickrs** [comment]
thanks a lot, i found it :)

i have one quest, my fhacontrol says, im earning 1.200.000 ppd /day,

but in my fah-web in stanford, only i have 77.407 score, and  7 wu only,
 my machine is up about 17hs mining

its strange, i spected about of 800 000 score. what im doing wrong?

thanks

**Comment by Hou5e** [comment]
The Folding@Home servers have about a 2-3 hour delay from when your computer competes a Work Unit (WU), until when you can see how many Folding points you received.
The Extreme OverClocking (EOC) http://folding.extremeoverclocking.com website stats are very useful.

The passkey gets you the **quick return bonus** after you have submitted 10 Work Units. Your points will be higher after that initial period.

So, just be patient for the first day or two.


CureCoin is distributed daily. You can login to CryptoBullions to check the status, and it takes a day or two for your first payout.

FoldingCoin distributions are monthly, on the first Saturday after the end of the month for points earned in the previous month.
The FoldingCoin Distribution server only runs once a night, then you can see your information on the distribution page.

For now, to find out how much FLDC you have earned for a day, you can use this:
http://foldingcoin.xyz/?token=FLDC&total=250000&start=2017-08-20&end=2017-08-21
Where you adjust the date ranges in the web link for a day, press the 'Show Stats' button, and Find (Ctrl+F) your Bitcoin address at the top for daily Folding@Home points and at the bottom for daily FLDC.

**Comment by rickrs** [comment]
thanks again, i found my address, last question

this showup in the site

1KSNzcq5fU6b1E8au3JQxdsHNyKzatmLD 20300
1KSNzcq5fU6b1E8au3JQxdsHNyKzatmLD, 6.89637733

how many fdlc i have? 6 or 20.300?

Rick

**Comment by Hou5e** [comment]
The top number is Folding@Home points.
The bottom number on the web page is in FLDC.

So: 6.89637733 FLDC

Also, remember there may be some additional configuration needed in the Folding@Home software for the number of CPU cores to use, and the number of GPUs to use. Those settings aren't always automatically setup by the Folding@Home software very well.

Note: In general, you will want to have 1 CPU core available for each GPU. If you've got a GPU, then possibly turning off CPU folding may yield better results.

If you have a laptop, the Chrome plugin might do better for low-power devices.

**Comment by rickrs** [comment]
fldc is gone? i cant see my stats

tks

**Comment by Hou5e** [comment]
Nope, the stats from Stanford's servers look like they were offline for about 15 hours yesterday. That happens a few times a month. You can look on EOC, and see the missing 3-hour stats, and then the stats catch-up later:
http://folding.extremeoverclocking.com/team_summary.php?s=&t=224497

The FLDC distributions are monthly, so it doesn't really have any impact, normally. You'll just have to wait a day or two when that happens. You're better off just monitoring your Points Per Day (PPD) stats on EOC.

**Comment by Hou5e** [comment]
If you have any additional questions, please use the FoldingCoin Slack or CureCoin Slack:
  * [FoldingCoin New User Slack Signup Link](http://slack.foldingcoin.net/) -- [FoldingCoin Slack](https://foldingcoin.slack.com/)
  * [CureCoin New User Slack Signup Link](http://slack.curecoin.net:30000/) -- [CureCoin Slack](https://curecoin.slack.com/)

Thanks for using the FoldingBrowser!
